### PR TITLE
Fixed the outdated executables generation pipeline

### PR DESCRIPTION
**Pull request by gaya-**
Now the first two tutorials for roslisp should work perfectly, especially the [Organizing Files](http://wiki.ros.org/roslisp/Tutorials/OrganizingFiles) one

### CODE REVIEW

**Comment by gaya-** [comment]
It seems that I finally nailed it down. So, the way things worked before now was that CMake would collect all the targets for Lisp executables in a chain to make sure that they are always compiled sequentially. That was done using the ```${ROSLISP_EXECUTABLES}``` variable. That variable is defined in the top-level of the CMake project, i.e. in the top-level of the catkin workspace. Each Lisp package would add its executables to this variable, however, because CMake only gives projects access to their parent scope and we have multiple layers of scoping due to metapackages etc, the ```${ROSLISP_EXECUTALBES}``` inside of one ROS package was not the same variable as in the top-level workspace. To put it simpler, CMake doesn't support global variables and for chaining all the executables in all the packages of one workspace we would need such a global variable.

The error that we were getting was caused by two catkin packages having the same dependency (```ros-load-manifest```) and trying to compile it at the same time. The solution I came up with is to add an extra target, which compiles ```ros-load-manifest``` and make sure that any Lisp executable from any catkin package would always depend on that target first.

This doesn't solve the original problem of chaining all the executables into one compilation queue. The executables within one catkin package are compiled sequentially, but those from different packages are still compiled in parallel. This can get problematic if they have any other common dependency other than ```ros-load-manifest```.

One solution to this that I see would be to use cached variables to somehow substitute the global variables but that would be too dirty and hacky because of the nature of cached variables. The other solution, as mentioned before, would be to call the Lisp compiler when compiling a roslisp package through catkin, which would be nice to have in general...

@airballking, could you please test this and merge it in? As a reminder, if you can recall, previously the compilation would succeed from time to time due to the non-deterministic nature of compiling with multiple threads, so please test it 3-5 times. And, also, don't forget to clean the Common Lisp cache each time.

**Comment by gaya-** [comment]
I've simplified the way the executables are generated now. I agree with @airballking that the old approach with compiling the Lisp code was error-prune and hard to maintain for the build farm (its CMake part was also quite ugly), so I guess we can leave that for better times. However, the alternative approach with [creating custom bash scripts that would invoke sbcl](http://wiki.ros.org/roslisp/Tutorials/OrganizingFiles#Using_roslisp_in_scripts) wasn't completely satisfactory for me, so I automated it using CMake (see the new ``add_lisp_executable``) and as a result:

* when distributing the code one doesn't need to include the executable scripts into their source tree, it is only required to have one line with ``add_lisp_executable`` in the CMakeLists and the executable will be automatically generated in the ``devel`` directory (``${CATKIN_PACKAGE_BIN_DESTINATION}``)
* for people new to roslisp and bash in general, calling ``add_lisp_executable`` in CMakeLists should be easier to understand than the bash magic (especially the ``"true";`` part is confusing)

@airballking, please take a look and let me know what you think.

I haven't got rid of the old approach yet, it is still there in the ``add_compiled_lisp_executable`` function, I will probably get rid of that completely on the master branch and leave it somewhere on a separate branch for future reference.

**Comment by gaya-** [comment]
@airballking ping :)

**Comment by airballking** [comment]
I'll have a look. I can't promise any deadline because my family have priority during my parental leave..

**Comment by tprk77** [comment]
Just my opinion... Sorry for interjecting.

It would be really nice to have this. Especially for the upcoming Jade release.

A few months ago, I wanted to try `roslisp`, so I went to try the tutorials. I downloaded them and did the usual `catkin_make`, but it failed. And that's basically when I gave up.

(I tried debugging the build for a while, but to no avail. Working on a build system is though, and often under appreciated, so I applaud @gaya- for her efforts!)

I know Lisp is much different from C++, etc, and you are typically using the REPL, but I also want to run programs outside of the REPL (like on a robot). Not being able to build stand-alone executable with the usual ROS tools is kind of a show-stopper.

**Comment by airballking** [comment]
@tprk77 Thanks for the encouraging comments! :)

**Comment by airballking** [comment]
Finally got around testing this. Building and installing executables seems to work. @gaya- Thanks for providing this cool feature!

For my own reference, I put my simple test here:
https://github.com/airballking/roslisp_executable_tests

**Pull request merged**
